repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        name: mypy
        always_run: true
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        name: ruff-check
        always_run: true
        args: [--fix]
      - id: ruff-format
        name: ruff-format
        always_run: true
